[package]
name = "rafs"
version = "0.1.0"
authors = ["The Nydus Developers"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arc-swap = "0.4.6"
base64 = { version = ">=0.12.0", optional = true }
bitflags = ">=1.1.0"

lazy_static = "1.4.0"
libc = "0.2"
log = "0.4"
spmc = "0.3.0"
lz4-sys = "1.9.2"
nix = "0.17.0"
blake3 = "0.3.6"

futures = "0.3"
anyhow = "1.0.35"
flate2 = { version = "1.0", features = ["miniz-sys"], default-features = false }

serde = { version = ">=1.0.27", features = ["serde_derive", "rc"] }
serde_json = ">=1.0.9"
serde_with = { version = "1.6.0", features = ["macros"] }
sha2 = { version = "0.9.1" }
sha-1 = { version = "0.9.1", optional = true }
hmac = { version = "0.8.1", optional = true }
url = { version = "2.1.1", optional = true }
vm-memory = ">=0.2.0"
nydus-utils = { path = "../utils" }
storage = { path = "../storage", features = ["backend-localfs"] }

fuse-rs = { git = "https://github.com/cloud-hypervisor/fuse-backend-rs.git", rev = "cfd2cca" }


[dev-dependencies]
vmm-sys-util = "0.6.0"

[features]
fusedev = ["fuse-rs/fusedev"]
virtio-fs = ["fuse-rs/virtiofs"]
vhost-user-fs = ["fuse-rs/vhost-user-fs"]
backend-oss = ["storage/backend-oss"]
backend-registry = ["storage/backend-registry"]
